### ISSUE TITLE
Async vs sync execution is not consistent with jQuery.ready

### ISSUE THREAD

**Issue by stof** [nuclei/readyjs#1]
jQuery.ready always calls the callback in an synchronous way (so code just after the `ready` call always gets executed before the callback).
This library has an different behavior depending on whether the DOM is already loaded or no. If it is already loaded, the callback is executed synchronously. This means it cannot be used as a direct replacement.

**Comment by lukasoppermann** [comment]
Hey, I understand the issue. Would be able to send a PR to solve this?
