### ISSUE TITLE
window load event fallback

### ISSUE THREAD

**Issue by Johann-S** [nuclei/readyjs#4]
Hi thanks for your package 👍 

jQuery ensure the ready event is triggered by adding a fallback to the load event, I think it would be a good addition to your package.
See: https://github.com/jquery/jquery/blob/master/src/core/ready.js#L61-L81

**Comment by lukasoppermann** [comment]
You are referring to `window.addEventListener( "load", completed );` ?

If so, I would appreciate a PR.

**Comment by Johann-S** [comment]
Yep 👍 

Sure 👍
